/*
 * Generates the starter-pack assets module in Contentstack CLI (`csdx`) import
 * format, so `csdx cm:stacks:import` brings a hero image into the stack and the
 * seed banner has a real picture out of the box.
 *
 *   node import-export/starter-pack/generate-assets.mjs   # run BEFORE generate-seed.mjs
 *
 * Ships ONE placeholder hero banner PNG, generated here (no binary is
 * hand-committed, nothing external is fetched). A SAP developer replaces it with
 * their own image in the Contentstack UI. `generate-seed.mjs` reads the asset
 * record this writes and wires it into `seed_banner.media`.
 *
 * csdx asset export layout (matches @contentstack/cli import):
 *   assets/assets.json                       -> { "1": "index.json" }  (chunk index)
 *   assets/index.json                        -> { <uid>: <record> }    (the chunk)
 *   assets/folders.json                      -> []                     (asset at root)
 *   assets/files/<uid>/<filename>            -> the binary
 *   assets/files/<uid>/_contentstack_<uid>.json -> a copy of <record>
 * Placeholder uid is remapped by csdx on import (like the seed entry uids).
 */
import { writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { deflateSync } from 'node:zlib';

const PACK = dirname(fileURLToPath(import.meta.url));
const ASSETS = join(PACK, 'assets');

export const HERO_ASSET = {
  uid: 'seed_hero_banner',
  filename: 'hero-banner.png',
  title: 'Hero Banner (placeholder)',
  description: 'Placeholder hero banner shipped with the starter pack — replace with your own image.',
  content_type: 'image/png',
};

// --- minimal PNG encoder (truecolor RGB, no dependencies) ---
function crc32(bytes) {
  let crc = 0xffffffff;
  for (let i = 0; i < bytes.length; i++) {
    crc ^= bytes[i];
    for (let j = 0; j < 8; j++) crc = crc & 1 ? (crc >>> 1) ^ 0xedb88320 : crc >>> 1;
  }
  return (crc ^ 0xffffffff) >>> 0;
}
function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length, 0);
  const typeBuf = Buffer.from(type, 'ascii');
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([typeBuf, data])), 0);
  return Buffer.concat([len, typeBuf, data, crc]);
}
function bannerPng(width, height) {
  // Diagonal blend between two indigo/violet tones — a clean, brand-neutral hero.
  const left = [30, 26, 77]; // #1E1A4D deep indigo
  const right = [108, 75, 244]; // #6C4BF4 violet
  const raw = Buffer.alloc(height * (1 + width * 3));
  for (let y = 0; y < height; y++) {
    const rowStart = y * (1 + width * 3);
    raw[rowStart] = 0; // filter: none
    for (let x = 0; x < width; x++) {
      // horizontal gradient with a subtle vertical darkening toward the bottom
      const tx = x / (width - 1);
      const shade = 1 - (y / (height - 1)) * 0.18;
      const p = rowStart + 1 + x * 3;
      for (let c = 0; c < 3; c++) {
        raw[p + c] = Math.round((left[c] + (right[c] - left[c]) * tx) * shade);
      }
    }
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 2; // color type: truecolor RGB
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw)),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

const png = bannerPng(1200, 400);
const { uid, filename, title, description, content_type } = HERO_ASSET;
const record = {
  uid,
  urlPath: `/assets/${uid}`,
  status: true,
  content_type,
  file_size: String(png.length),
  tag: [],
  filename,
  url: '', // regenerated by Contentstack on import (the local file is uploaded)
  is_dir: false,
  parent_uid: null,
  _version: 1,
  title,
  description,
  publish_details: [], // published manually in the UI after import, like the seed entries
};

rmSync(ASSETS, { recursive: true, force: true });
const fileDir = join(ASSETS, 'files', uid);
mkdirSync(fileDir, { recursive: true });
writeFileSync(join(fileDir, filename), png);
writeFileSync(join(fileDir, `_contentstack_${uid}.json`), JSON.stringify(record));
writeFileSync(join(ASSETS, 'assets.json'), JSON.stringify({ 1: 'index.json' }));
writeFileSync(join(ASSETS, 'index.json'), JSON.stringify({ [uid]: record }));
writeFileSync(join(ASSETS, 'folders.json'), JSON.stringify([]));

console.log(`wrote assets module (1 placeholder asset, ${png.length} bytes) to ${ASSETS}`);
